import { createRouter, createWebHistory } from 'vue-router'

export const router = createRouter({
  history: createWebHistory(),
  routes: [
    { path: `${import.meta.env.BASE_URL}/`, redirect: `${import.meta.env.BASE_URL}/home/` },
    { path: `${import.meta.env.BASE_URL}/about/`, name: 'about', component: () => import('./components/About.vue') },
    { path: `${import.meta.env.BASE_URL}/home/`, name: 'home', component: () => import('./components/Home.vue') },
    { path: `${import.meta.env.BASE_URL}/accounts/list/`, name: 'accounts_list', component: () => import('./components/AccountsList.vue') },
    { path: `${import.meta.env.BASE_URL}/assets/report/`, name: 'assetsreport', component: () => import('./components/AssetsReport.vue') },
    { path: `${import.meta.env.BASE_URL}/banks/list/`, name: 'banks_list', component: () => import('./components/BanksList.vue') },
    { path: `${import.meta.env.BASE_URL}/concepts/catalog/`, name: 'concepts_catalog', component: () => import('./components/ConceptsCatalog.vue') },
    { path: `${import.meta.env.BASE_URL}/currencies/`, name: 'currencies', component: () => import('./components/Currencies.vue') },
    { path: `${import.meta.env.BASE_URL}/investments/list/`, name: 'investments_list', component: () => import('./components/InvestmentsList.vue') },
    { path: `${import.meta.env.BASE_URL}/orders/list/`, name: 'orders_list', component: () => import('./components/OrdersList.vue') },
    { path: `${import.meta.env.BASE_URL}/maintenance/quotes/`, name: 'maintenance_quotes', component: () => import('./components/MaintenanceQuotes.vue') },
    { path: `${import.meta.env.BASE_URL}/products/ranges/`, name: 'products_ranges', component: () => import('./components/ProductsRanges.vue') },
    { path: `${import.meta.env.BASE_URL}/products/comparation/list/`, name: 'products_comparation_list', component: () => import('./components/ProductsComparationList.vue') },
    { path: `${import.meta.env.BASE_URL}/products/search/`, name: 'products_search', component: () => import('./components/ProductsSearch.vue') },
    { path: `${import.meta.env.BASE_URL}/products/catalog/update/`, name: 'products_catalog_update', component: () => import('./components/MaintenanceCatalogsUpdate.vue') },
    { path: `${import.meta.env.BASE_URL}/products/update/`, name: 'products_update', component: () => import('./components/ProductsUpdate.vue') },
    { path: `${import.meta.env.BASE_URL}/reports/annual/`, name: 'reports_annual', component: () => import('./components/ReportsAnnual.vue') },
    { path: `${import.meta.env.BASE_URL}/reports/concepts/`, name: 'reports_concepts', component: () => import('./components/ReportsConcepts.vue') },
    { path: `${import.meta.env.BASE_URL}/reports/derivatives/`, name: 'reports_derivatives', component: () => import('./components/ReportsDerivatives.vue') },
    { path: `${import.meta.env.BASE_URL}/reports/dividens/`, name: 'reports_dividends', component: () => import('./components/ReportsDividends.vue') },
    { path: `${import.meta.env.BASE_URL}/reports/investmentsclasses/`, name: 'reports_investments_classes', component: () => import('./components/ReportsInvestmentsClasses.vue') },
    { path: `${import.meta.env.BASE_URL}/reports/investments/lastoperation/`, name: 'reports_lastoperation', component: () => import('./components/ReportsInvestmentsLastOperation.vue') },
    { path: `${import.meta.env.BASE_URL}/reports/annualrevaluation/`, name: 'reports_annualrevaluation', component: () => import('./components/ReportsAnnualRevaluation.vue') },
    { path: `${import.meta.env.BASE_URL}/reports/investmentsoperations/current/`, name: 'reports_investmentsoperations_current', component: () => import('./components/ReportsCurrentInvestmentsOperations.vue') },
    { path: `${import.meta.env.BASE_URL}/reports/ranking/`, name: 'reports_ranking', component: () => import('./components/ReportsRanking.vue') },
    { path: `${import.meta.env.BASE_URL}/reports/evolution/`, name: 'reports_evolution', component: () => import('./components/ReportsEvolution.vue') },
    { path: `${import.meta.env.BASE_URL}/reports/zerorisk/`, name: 'reports_zero_risk', component: () => import('./components/ReportsZeroRisk.vue') },
    { path: `${import.meta.env.BASE_URL}/reports/evolution/chart/`, name: 'reports_evolution_chart', component: () => import('./components/ChartEvolutionAssets.vue') },
    { path: `${import.meta.env.BASE_URL}/settings/`, name: 'settings', component: () => import('./components/Settings.vue') },
    { path: `${import.meta.env.BASE_URL}/statistics/`, name: 'statistics', component: () => import('./components/Statistics.vue') },
    { path: `${import.meta.env.BASE_URL}/strategies/list/`, name: 'strategies_list', component: () => import('./components/StrategiesList.vue') },
    { path: `${import.meta.env.BASE_URL}/widgets/`, name: 'widgets', component: () => import('./components/Widgets.vue') },
    { path: `${import.meta.env.BASE_URL}/widgets/chartpie/`, name: 'widgets_chartpie', component: () => import('./components/WidgetsChartPie.vue') },
    { path: `${import.meta.env.BASE_URL}/widgets/mydatepicker/`, name: 'widgets_mydatepicker', component: () => import('./components/WidgetsMyDatePicker.vue') },
    { path: `${import.meta.env.BASE_URL}/widgets/mydatetimepicker/`, name: 'widgets_mydatetimepicker', component: () => import('./components/WidgetsMyDateTimePicker.vue') },
    { path: `${import.meta.env.BASE_URL}/widgets/mymonthpicker/`, name: 'widgets_mymonthpicker', component: () => import('./components/WidgetsMyMonthPicker.vue') },
  ]
})
